---
title: "Reproducibility Report for Mechanisms of Meditation: Investigating the Components and Covariates of a Single Session of Meditation by Taylor E. Bondi (2021, Doctoral Dissertation)"
author: "Quan Tang (qutang@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

This dissertation, titled "The Mechanism of Meditation: A Study on the Components and Covariates of a Single Meditation Session", mainly explores whether a single brief meditation practice can enhance well-being (operationalized as reduction of state stress and anxiety), and further examines the underlying mechanisms (expectations and thought valence) and situational factors. The author designed four experiments, comparing meditation condition with control condition (using ANCOVA), different components of the meditation, testing placebo and labeling effects, and conducting exploratory analysis at the end. The conclusion is that even a single-session meditation can bring about a considerable improvement in well-being. Moreover, expectations and thought valence play an important role in this process. The research results of the first chapter show that a 20-minute mindfulness meditation can significantly reduce state stress and state anxiety, with better effects than the control group. At the same time, meditation is more effective on dealing with negative thought than relaxation exercises. 

** Apart from all the preparatory analyses, what I aim to replicate is the outcome related to the meditation mechanism. That is, the interaction effects between thought valence and conditions on state stress and anxiety reduction. **  

During the initial stage of examining the effects of meditation, I will incorporate an ANOVA with conditions (meditation vs. control) and test points (pre-test vs. post-test) as independent variables, and state stress, state anxiety, and trait anxiety as dependent variables. The purpose is to prevent the loss of information when compositing the pre-test and post-test data.

In addition, apart from using Analysis of Covariance (ANCOVA), I also plan to attempt using linear mixed model (LMM) to separately incorporate the pre-test and post-test (instead of combining them into one variable) to examine the effect of meditation, as well as the role of thought valence within the effect.

### Justification for choice of study

The main reason is related to my research interests. I am currently focusing on how to promote people’s well-being, using either changing thought valence by meditation or the reducting death anxiety. Dr. Bondi’s research provides clear and rigorous analysis on how meditation reduce state stress and anxiety, and what role thought valence plays in this process. Her result suggests that meditation is good at dealing with negative thoughts, which can contribute to well-being. The most interesting thing is she failed to replicate the result by herself in the second experiment. I tend to discuss the mechanistic role of thought valence in the effects of being present, as a component of meditation, on well-being within the experimental control and manipulation design of the first year project. Therefore, I have to confirm that thought valence has real effect on well-being. 

### Anticipated challenges

1. Due to the incomplete information of the variables reported in the study, I would like to seek the original data from the authors of the paper in order to generate the simulation data.
2. For some variables, it might be necessary to assume that the data follows a normal distribution.

### Links

Project repository (on Github): https://github.com/qutang123/bondi2021.git

Original paper (as hosted in your repo): https://github.com/qutang123/bondi2021/blob/7e24871f1073cf9826759e85d40d99d2692410ac/original_paper/original_paper.pdf

Link of final project proposal: https://github.com/qutang123/bondi2021/blob/aaaf443a7b4cd80e19587de0a8e3772621f149b3/writeup/Reproducibility%20Report.qmd

## Methods

### Description of the steps required to reproduce the results

#### Data Generation 

The data will be generated based on R/Python. I will generate the data based on the mean, standard deviation and correlation coefficient provided in the original article and the ditributions of each variabe porvided by the author. The variables simulated will include the composite scores of:
state stress (both pre- and post-test, continuous variable, normal distribution); 
state anxiety (both pre- and post-test, continuous variable, normal distribution); 
trait anxiety (both pre- and post-test, continuous variable, normal distribution); 
thought valence (post-test only, discrete variable, normal distribution); 
conditions （categorical variable, binomial distribution）, based on the means, SDs, and correlations at participant-level. 

#### Data Analysis

The data analysis will rely on R. The full pipeline is: 
0. data preparation for reduction of state stress, state anxiety, and trait anxiety;
1. Descriptive statistics for all variables by conditions;
2. zero-order correlation analysis for all variables;
3. ANOVA (for effects of meditation) with conditions (between-subjects) and test points (within-subjects) as independent variables, state stress, state anxiety, and trait anxiety as dependent variables;
4. ANCOVAs (for the role of thought valence in meditation) with conditions and thought valence as independent variables, state stress and state anxiety as dependent variables;
5. LMMs (for the role of thought valence in meditation with the data of both pre- and post-test) with conditions, thought valence, and test points as independent variables, state stress, state anxiety, and trait anxiety as dependent variables, and subject ID as random effect.
The last two steps are the key results of reproduction. 

### Differences from original study

1. Since a normal distribution was assumed, this may differ from the original study. 
2. There may be slight differences between the generated data and the actual data.
3. The verson of R used for the original data analysis is different from those currently in use. 

Note. The additional ANOVA and LMM Analysis does not involve data generation and does not affect the analysis results.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.

Success criterion is When I input the original data, I could obtain the same results as the original article, and when I input the simulated data, the significance was consistent with that of the original article. 

### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).

For the descriptive statistics and correlation analysis, which are exams for the data simulation, I hope the results I obtain can be as close as possible to the original literature. Therefore, generating the data might require several attempts.

For ANCOVAs and LMMs, I hope they can separately detect the conditions * thought valence interaction and conditions * thought valence * test points interaction. In fact, all of this also depends on the aforementioned data generation.

## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
